export const PATH = {
  HOME: '/',
  MARKET: {
    PATH: '/market/:category',
    REDIRECT: '/market',
    ALL: '/market/all',
    COLLECTION: '/market/collection',
    EMOTICON: '/market/emoticon',
    FLOWER: '/market/flower',
    PLANTS: '/market/plants',
    MUSHROOM: '/market/mushroom',
    ROCK: '/market/rock',
    WOODEN: '/market/wooden',
    LIGHT: '/market/light',
  },
  MARKET_DETAIL: '/detail',
  MARKET_REGISTER: '/register',
  ITEM_DETAIL: '/item',
  ASSETS: '/assets',
  DASHBOARD: '/dashboard',
};
