name: Build (Dev)

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: ls ${{ github.workspace }}
      - run: docker build -t ${{ github.repository }}-${{ github.ref }} -f Dockerfile.local .
